package request

type RequestCreateVinculacion struct {

	Name							string	`json:"name"`
	Lastname						string	`json:"lastname"`
	Type_Doc						string	`json:"type_doc"`
	Num_Doc							string	`json:"num_doc"`
	Nationality						string	`json:"nationality"`
	Sex								string	`json:"sex"`
	Place_Birth						string	`json:"place_birth"`
	Day_Birth						string	`json:"day_birth"`
	Status_Civil					string	`json:"status_civil"`
	Tel_Resi						string	`json:"tel_resi"`
	Tel_Cel							string	`json:"tel_cel"`
	Tel_ofi							string	`json:"tel_ofi"`
	Dir_Resi						string	`json:"dir_resi"`
	City							string	`json:"city"`
	Cod_Postal						string	`json:"cod_postal"`
	Nom_Business					string	`json:"nom_business"`
	Type_Business					string	`json:"type_business"`
	Cargo							string	`json:"cargo"`
	Dir_Business					string	`json:"dir_business"`
	Anos_Business					string	`json:"anos_business"`
	City_Business					string	`json:"city_business"`
	Resident						string	`json:"resident"`
	Num_Security					string	`json:"num_security"`
	Number_Fax						string	`json:"number_fax"`
	Email							string	`json:"email"`
	Correspondence					string	`json:"correspondence"`
	Confirmations					string	`json:"confirmations"`
	Account_Num1					string	`json:"account_num_1"`
	Account_Num2					string	`json:"account_num_2"`
	Account_Num3					string	`json:"account_num_3"`
	Account_Type1					string	`json:"account_type_1"`
	Account_Type2					string	`json:"account_type_2"`
	Account_Type3					string	`json:"account_type_3"`
	Institution1					string	`json:"institution_1"`
	Institution2					string	`json:"institution_2"`
	Institution3					string	`json:"institution_3"`
	Custodian_Account				string  `json:"custodian_account"`
	Institution_Other				string  `json:"institution_other"`
	Knowledge						string	`json:"knowledge"`
	Market_Cycle					string	`json:"market_cycle"`
	Academic_Level					string	`json:"academic_level"`
	Annual_Income					string	`json:"annual_income"`
	Total_Equity					string	`json:"total_equity"`
	Liquid_Assets					string	`json:"liquid_assets"`
	Investment_Objectives			string	`json:"investment_objectives"`
	Tolerance_Risk					string	`json:"tolerance_risk"`
	Total_Patrimony1				string	`json:"total_patrimony_1"`
	Total_Patrimony2				string	`json:"total_patrimony_2"`
	Total_Assets1					string	`json:"total_assets_1"`
	Total_Assets2					string	`json:"total_assets_2"`
	Source_Funds					string 	`json:"source_funds"`
	Attachments						string	`json:"attachments"`
	Bank_References_Institution1	string	`json:"bank_references_institution_1"`
	Bank_References_Institution2	string	`json:"bank_references_institution_2"`
	Bank_References_Institution3	string	`json:"bank_references_institution_3"`
	Bank_References_Address1		string	`json:"bank_references_address_1"`
	Bank_References_Address2		string	`json:"bank_references_address_2"`
	Bank_References_Address3		string	`json:"bank_references_address_3"`
	Bank_References_Phone1			string	`json:"bank_references_phone_1"`
	Bank_References_Phone2			string	`json:"bank_references_phone_2"`
	Bank_References_Phone3			string	`json:"bank_references_phone_3"`
	Other_Collected_Proceeds1		string	`json:"other_collected_proceeds_1"`
	Other_Collected_Proceeds2		string	`json:"other_collected_proceeds_2"`
}